spring.datasource:
  url: jdbc:postgresql://localhost/mydb
  username: USER_NAME
  password: PASSWORD
  driver-class-name: org.postgresql.Driver


server:
  port: 8080
springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true
