spring.datasource:
  url: jdbc:postgresql://localhost/InvoiceDatabase
  username: postgres
  password: fortment
  driver-class-name: org.postgresql.Driver


server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true